"""users table

Revision ID: 491ec1f079a5
Revises: 
Create Date: 2018-08-13 14:26:08.755293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491ec1f079a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_screen_name'), 'user', ['screen_name'], unique=True)
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('twt_text', sa.Text(length=280), nullable=True),
    sa.Column('twt_date', sa.Date(), nullable=True),
    sa.Column('twt_hash', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_twt_hash'), 'tweets', ['twt_hash'], unique=False)
    op.create_index(op.f('ix_tweets_twt_text'), 'tweets', ['twt_text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweets_twt_text'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_twt_hash'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_index(op.f('ix_user_screen_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
